In [55]:
import numpy as np

In [71]:
N=1000000

In [101]:
X = np.random.randn(N, 2)
X[:,0]

array([ 0.01193162,  0.15766358, -1.29717173, ...,  0.25135645,
       -0.61015633, -0.17175902])

In [73]:
l=np.shape(X)[0]
l

1000000

In [74]:
m = np.sum(X, axis=0)/l
m

array([-0.00044674, -0.00201722])

In [83]:
sd = np.sum((X-m)**2, axis=0)/l

In [79]:
x = np.random.randn(1,2)

In [97]:
exponent = -((x-m)**2/(2*sd)).flatten()
exponent

array([-0.08820514, -1.07535114])

In [99]:
np.product(np.exp(exponent))

0.31237331875673108